#!/usr/bin/env bash
# Configures nginx to serve a custom X-Served-By header with the
# server's hostname.
# shellcheck disable=SC2154

apt-get update -y
apt-get install -y nginx

sed -i "/http {/a \\\tadd_header X-Served-By \$hostname;" /etc/nginx/nginx.conf

echo "Hello World!" > /var/www/html/index.nginx-debian.html

service nginx start
service nginx restart
